sonar.projectKey=transaction-service
sonar.projectName=transaction-service
sonar.sources=services/transaction-service/src
sonar.exclusions=**/node_modules/**,**/*.test.js,**/coverage/**
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=javascript:S7785
sonar.issue.ignore.multicriteria.e1.resourceKey=services/transaction-service/src/index.js
